spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Monitoring
    username: postgres
    password: ********
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,httptrace,loggers,threaddump
  endpoint:
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      path: /
      threshold: 1GB
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

#Need to check use of it
management.metrics.tags.application: monitoring-app